version: '2'

services:
  web:
    build: .
    container_name: web
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    links:
      - db
#    tty: true
  db:
    image: mysql:latest
    container_name: db
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
       MYSQL_DATABASE: anime_v4
       MYSQL_ROOT_PASSWORD: lamptest
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
     - PMA_ARBITRARY=1
     - PMA_HOST=db
     - PMA_USER=root
     - PMA_PASSWORD=lamptest
    restart: always
    ports:
     - 8080:80
    volumes:
     - /sessions
